/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp1;

/**
 *
 * @author Yan Revuz
 */
public class ExerciceQuatreBoutons extends javax.swing.JFrame {
    //Tous les etat de notre Automate
    private enum State {
        PRIMTEMPS, //etat initial
        ETE,
        HIVER,
        AUTOMNE
    }
    
     /* Etat en cours*/
    private State etatEnCours;
    
    /**
     * Creates new form ExerciceQuatreBoutons
     */
    public ExerciceQuatreBoutons() {
        initComponents();
        init();
    }
    
     /* Methode d'initialisation */
    public void init(){
        setEnabledPrimptempsButton(true);
        setEnabledEteButton(false);
        setEnabledAutomneButton(false);
        setEnabledHiverButton(false);
        changeState(State.PRIMTEMPS);
    }
    
    /* Permet de desactiver / activer le boutton Primptemps*/
    public void setEnabledPrimptempsButton(boolean enabled){
        this.boutonPrimtemps.setEnabled(enabled);
    }
    
    /* Permet de desactiver / activer le boutton été */
    public void setEnabledEteButton(boolean enabled){
        this.boutonEte.setEnabled(enabled);
    }
    
    /* Permet de desactiver / activer le boutton Hiver */
    public void setEnabledHiverButton(boolean enabled){
        this.boutonHiver.setEnabled(enabled);
    }
    
    /* Permet de desactiver / activer le boutton Automne */
    public void setEnabledAutomneButton(boolean enabled){
        this.boutonAutomne.setEnabled(enabled);
    }
    
    /* Permet de changer d'état */
    public void changeState(State state){
        this.etatEnCours = state;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boutonEte = new javax.swing.JButton();
        boutonAutomne = new javax.swing.JButton();
        boutonPrimtemps = new javax.swing.JButton();
        boutonHiver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        boutonEte.setText("Eté");
        boutonEte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonEteActionPerformed(evt);
            }
        });

        boutonAutomne.setText("Autômne");
        boutonAutomne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAutomneActionPerformed(evt);
            }
        });

        boutonPrimtemps.setText("Primptemps");
        boutonPrimtemps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonPrimtempsActionPerformed(evt);
            }
        });

        boutonHiver.setText("Hiver");
        boutonHiver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonHiverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boutonHiver, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(boutonEte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(boutonAutomne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boutonPrimtemps, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boutonAutomne, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(boutonEte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boutonHiver, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(boutonPrimtemps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutonPrimtempsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonPrimtempsActionPerformed
        switch(this.etatEnCours){
            case PRIMTEMPS:
                setEnabledPrimptempsButton(false);
                setEnabledEteButton(true);
                setEnabledAutomneButton(false);
                setEnabledHiverButton(false);
                changeState(State.ETE);
                break;
            case ETE:
                /* Interdit */
                break;
            case AUTOMNE:
                /* Interdit */
                break;
            case HIVER:
                /* Interdit */
                break;
            default:
                /* Interdit */
        }
    }//GEN-LAST:event_boutonPrimtempsActionPerformed

    private void boutonAutomneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAutomneActionPerformed
        switch(this.etatEnCours){
            case PRIMTEMPS:
                /* Interdit */
                break;
            case ETE:
                /* Interdit */
                break;
            case AUTOMNE:
                setEnabledPrimptempsButton(false);
                setEnabledEteButton(false);
                setEnabledAutomneButton(false);
                setEnabledHiverButton(true);
                changeState(State.HIVER);
                break;
            case HIVER:
                /* Interdit */
                break;
            default:
                /* Interdit */
        }
    }//GEN-LAST:event_boutonAutomneActionPerformed

    private void boutonEteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonEteActionPerformed
        switch(this.etatEnCours){
            case PRIMTEMPS:
                /* Interdit */
                break;
            case ETE:
                setEnabledPrimptempsButton(false);
                setEnabledEteButton(false);
                setEnabledAutomneButton(true);
                setEnabledHiverButton(false);
                changeState(State.AUTOMNE);
                break;
            case AUTOMNE:
                /* Interdit */
                break;
            case HIVER:
                /* Interdit */
                break;
            default:
                /* Interdit */
        }
    }//GEN-LAST:event_boutonEteActionPerformed

    private void boutonHiverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonHiverActionPerformed
        switch(this.etatEnCours){
            case PRIMTEMPS:
                /* Interdit */
                break;
            case ETE:
                /* Interdit */
                break;
            case AUTOMNE:
                /* Interdit */
                break;
            case HIVER:
                setEnabledPrimptempsButton(true);
                setEnabledEteButton(false);
                setEnabledAutomneButton(false);
                setEnabledHiverButton(false);
                changeState(State.PRIMTEMPS);
                break;
            default:
                /* Interdit */
        }
    }//GEN-LAST:event_boutonHiverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExerciceQuatreBoutons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExerciceQuatreBoutons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExerciceQuatreBoutons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExerciceQuatreBoutons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExerciceQuatreBoutons().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonAutomne;
    private javax.swing.JButton boutonEte;
    private javax.swing.JButton boutonHiver;
    private javax.swing.JButton boutonPrimtemps;
    // End of variables declaration//GEN-END:variables
}
