/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp1;

/**
 *
 * @author yan
 */
public class ExerciceBouton2a2 extends javax.swing.JFrame {
    
    //Tous les etat de notre Automate
    private enum State {
        INIT, //etat initial
        CLIQUE_B1_FIRST,
        CLIQUE_B2_FIRST,
        CLIQUE_B1_OR_B2,
        CLIQUE_B3_FIRST,
        CLIQUE_B4_FIRST
    }
    
    /* l'etat en cours */
    private State etatEnCours;
    /**
     * Creates new form ExerciceBouton2a2
     */
    public ExerciceBouton2a2() {
        initComponents();
        init();
    }
    
     /* Methode d'initialisation */
    public void init(){
         etatInit();
    }
    
    /* Permet de desactiver / activer le boutton Primptemps*/
    public void setEnabledButton1(boolean enabled){
        this.button1.setEnabled(enabled);
    }
    
    /* Permet de desactiver / activer le boutton été */
    public void setEnabledButton2(boolean enabled){
        this.button2.setEnabled(enabled);
    }
    
    /* Permet de desactiver / activer le boutton Hiver */
    public void setEnabledButton3(boolean enabled){
        this.button3.setEnabled(enabled);
    }
    
    /* Permet de desactiver / activer le boutton Automne */
    public void setEnabledButton4(boolean enabled){
        this.button4.setEnabled(enabled);
    }
    
    
    /* Permet de changer d'état */
    public void changeState(State state){
        this.etatEnCours = state;
    }
    
    /* Etat init */
    public void etatInit(){
        setEnabledButton1(true);
        setEnabledButton2(true);
        setEnabledButton3(false);
        setEnabledButton4(false);
        changeState(State.INIT);
    }
    
    public void etatCliqueB1First(){
        setEnabledButton1(true);
        setEnabledButton2(true);
        setEnabledButton3(false);
        setEnabledButton4(false);
        changeState(State.CLIQUE_B1_FIRST);
    }
    
    public void etatCliqueB2First(){
        setEnabledButton1(true);
        setEnabledButton2(true);
        setEnabledButton3(false);
        setEnabledButton4(false);
        changeState(State.CLIQUE_B2_FIRST);
    }
    
    public void etatCliqueB1B2(){
        setEnabledButton1(false);
        setEnabledButton2(false);
        setEnabledButton3(true);
        setEnabledButton4(true);
        changeState(State.CLIQUE_B1_OR_B2);
    }
    
    public void etatCliqueB3First(){
        setEnabledButton1(false);
        setEnabledButton2(false);
        setEnabledButton3(true);
        setEnabledButton4(true);
        changeState(State.CLIQUE_B3_FIRST);
    }
    
    public void etatCliqueB4First(){
        setEnabledButton1(false);
        setEnabledButton2(false);
        setEnabledButton3(true);
        setEnabledButton4(true);
        changeState(State.CLIQUE_B4_FIRST);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button1.setText("Bouton 1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setText("Bouton 2");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setText("Bouton 3");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        button4.setText("Bouton 4");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1)
                    .addComponent(button3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button2)
                    .addComponent(button4))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button1)
                    .addComponent(button2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button3)
                    .addComponent(button4))
                .addGap(105, 105, 105))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        switch(this.etatEnCours){
            case INIT:
                etatCliqueB1First();
                break;
            case CLIQUE_B1_FIRST:
                etatCliqueB1First();
                break;
            case CLIQUE_B2_FIRST:
                etatCliqueB1B2();
                break;
            case CLIQUE_B1_OR_B2:
                /* Interdit */
                break;
            case CLIQUE_B3_FIRST:
                /* Interdit */
                break;
            case CLIQUE_B4_FIRST:
                /* Interdit */
                break;
            default:
                /* Interdit */
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        switch(this.etatEnCours){
            case INIT:
                etatCliqueB2First();
                break;
            case CLIQUE_B1_FIRST:
                etatCliqueB1B2();
                break;
            case CLIQUE_B2_FIRST:
                etatCliqueB2First();
                break;
            case CLIQUE_B1_OR_B2:
                /* Interdit */
                break;
            case CLIQUE_B3_FIRST:
                /* Interdit */
                break;
            case CLIQUE_B4_FIRST:
                /* Interdit */
                break;
            default:
                /* Interdit */
        }
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        switch(this.etatEnCours){
            case INIT:
                /* Interdit */
                break;
            case CLIQUE_B1_FIRST:
                /* Interdit */
                break;
            case CLIQUE_B2_FIRST:
                /* Interdit */
                break;
            case CLIQUE_B1_OR_B2:
                etatCliqueB3First();
                break;
            case CLIQUE_B3_FIRST:
                etatCliqueB3First();
                break;
            case CLIQUE_B4_FIRST:
                etatInit();
                break;
            default:
                /* Interdit */
        }
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        switch(this.etatEnCours){
            case INIT:
                /* Interdit */
                break;
            case CLIQUE_B1_FIRST:
                /* Interdit */
                break;
            case CLIQUE_B2_FIRST:
                /* Interdit */
                break;
            case CLIQUE_B1_OR_B2:
                etatCliqueB4First();
                break;
            case CLIQUE_B3_FIRST:
                etatInit();
                break;
            case CLIQUE_B4_FIRST:
                etatCliqueB4First();
                break;
            default:
                /* Interdit */
        }
    }//GEN-LAST:event_button4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExerciceBouton2a2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExerciceBouton2a2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExerciceBouton2a2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExerciceBouton2a2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExerciceBouton2a2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    // End of variables declaration//GEN-END:variables
}
