package tp1;

/**
 *
 * @author Yan Revuz
 */
public class ExercicePoufCompteur extends javax.swing.JFrame {
    //Tous les etat de notre Automate
    public enum State {
        INITIAL, //etat initial
        INCREMNTE 
    }
    
    /* Etat en cours*/
    private State etatEnCours;
    
    /* Le compteur à afficher*/
    private int valeurCompteur;
    
    
    /*La valeur maximum du conpteur */
    private static final int VALEUR_MAX_COMPTEUR = 3;
    /**
     * Creates new form Exercice1
     */
    public ExercicePoufCompteur() {
        initComponents();
        init();
    }
    
    /* Methode d'initialisation */
    public void init(){
        setEnabledStopButton(false);
        setEnabledStartButton(true);
        setEnabledIncrementButton(false);
        initCompteur();
        printCompteur();
        changeState(State.INITIAL);
    }
    
    /* Permet de desactiver / activer le boutton Stop */
    public void setEnabledStopButton(boolean enabled){
        this.stop.setEnabled(enabled);
    }
    
    /* Permet de desactiver / activer le boutton Start */
    public void setEnabledStartButton(boolean enabled){
        this.start.setEnabled(enabled);
    }
    
    /* Permet de desactiver / activer le boutton Increment */
    public void setEnabledIncrementButton(boolean enabled){
        this.increment.setEnabled(enabled);
    }
    
    /* Permet de mettre le compteur à 0 */
    public void initCompteur(){
        this.valeurCompteur =0;
    }
    
    /* Permet d'incrementer le compteur */
    public void incrementCompteur(){
        this.valeurCompteur++;
    }
    
    /* Permet de changer la valeur du label */
    public void printCompteur(){
        this.compteurLabel.setText(this.valeurCompteur+"");
    }
    
    /* Permet de changer la valeur du label à POUF */
    public void printPouf(){
        this.compteurLabel.setText("POUF");
    }
    
    /* Permet de changer d'état */
    public void changeState(State state){
        this.etatEnCours = state;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        start = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        compteurLabel = new javax.swing.JLabel();
        increment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        stop.setText("Stop");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });

        compteurLabel.setText("0");

        increment.setText("+1");
        increment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incrementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(start, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(increment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(stop, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(compteurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(start, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(stop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(increment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(compteurLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        switch(this.etatEnCours){
            case INITIAL:
                initCompteur();
                printCompteur();
                setEnabledStartButton(false);
                setEnabledStopButton(true);
                setEnabledIncrementButton(true);
                changeState(State.INCREMNTE);
                break;
            case INCREMNTE:
                /* Interdit */
                break;
            default:
                /* Interdit */
        }
    }//GEN-LAST:event_startActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        switch(this.etatEnCours){
            case INITIAL:
                /* Interdit */
                break;
            case INCREMNTE:
                printPouf();
                setEnabledStartButton(true);
                setEnabledStopButton(false);
                setEnabledIncrementButton(false);
                changeState(State.INITIAL);
                break;
            default:
                /* Interdit */
        }
    }//GEN-LAST:event_stopActionPerformed

    private void incrementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incrementActionPerformed
        switch(this.etatEnCours){
            case INITIAL:
                /* Interdit */
                break;
            case INCREMNTE:
                if( this.valeurCompteur < VALEUR_MAX_COMPTEUR ){
                    incrementCompteur();
                    printCompteur();
                    setEnabledStartButton(false);
                    setEnabledStopButton(true);
                    setEnabledIncrementButton(true);
                    changeState(State.INCREMNTE);
                }else if(this.valeurCompteur == VALEUR_MAX_COMPTEUR ){
                    printPouf();
                    setEnabledStartButton(true);
                    setEnabledStopButton(false);
                    setEnabledIncrementButton(false);
                    changeState(State.INITIAL);
                }
                break;
            default:
                /* Interdit */
        }
    }//GEN-LAST:event_incrementActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExercicePoufCompteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExercicePoufCompteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExercicePoufCompteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExercicePoufCompteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExercicePoufCompteur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel compteurLabel;
    private javax.swing.JButton increment;
    private javax.swing.JButton start;
    private javax.swing.JButton stop;
    // End of variables declaration//GEN-END:variables
}
